// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckVPN():Promise<Array<string>>;

export function Connect(arg1:main.Settings):Promise<string>;

export function DeleteProfile(arg1:string):Promise<void>;

export function Diagnose():Promise<void>;

export function Disconnect():Promise<void>;

export function GetAutoStart():Promise<boolean>;

export function IsConnected():Promise<boolean>;

export function ListProfiles():Promise<Array<string>>;

export function LoadProfile(arg1:string):Promise<main.Settings>;

export function LoadSettings():Promise<main.Settings>;

export function Platform():Promise<string>;

export function SaveProfile(arg1:string,arg2:main.Settings):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;
