// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckVPN() {
  return window['go']['main']['App']['CheckVPN']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function Diagnose() {
  return window['go']['main']['App']['Diagnose']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetAutoStart() {
  return window['go']['main']['App']['GetAutoStart']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function LoadProfile(arg1) {
  return window['go']['main']['App']['LoadProfile'](arg1);
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function Platform() {
  return window['go']['main']['App']['Platform']();
}

export function SaveProfile(arg1, arg2) {
  return window['go']['main']['App']['SaveProfile'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}
